# NumPy

NumPy é um pacote fundamental para computação científica em Python, sendo usado como base para praticamente todos os outros. Suas capacidades incluem uma poderosa classe *array*, que pode representar vetores e matrizes, sofisticadas funções para manipulação de *arrays*, ferramentas para integração de códigos em C/C++ e Fortran, além de funções de álgebra linear e de geração de números aleatórios. Os *arrays* de NumPy também podem ser usados para armazenar dados de tipos genéricos, permitindo fácil integração com diferentes tipos de bases e bancos de dados. A documentação completa para todas as versões de NumPy pode ser encontrada em [numpy.org/doc](https://numpy.org/doc).

## A classe *array*

A classe *array* é o principal componente de NumPy e representa uma lista homogênea multidimensional, na forma de uma tabela de elementos (normalmente números), todos do mesmo tipo, indexada por tuplas de inteiros positivos. Um dimensão de um *array* é chamada de eixo (*axis*). Abaixo, temos dois exemplos de *arrays* (note sua criação por meio de listas):

In [ ]:
import numpy as np

a = np.array([1,2,1]) # Uma dimensão, 3 elementos, tipo inteiro
# print(len(a), a.dtype)
# print(a.shape, a.dtype)

#Duas dimensões, a primeira com 2 elementos e a segunda com 3
b = np.array([
    [1., 0., 1., 2.],
    [0., 1., 2., 4.]
])
# print(b.shape, len(b), b.dtype)
# display(b)

In [ ]:
c = [
    [1,2,3],
    [4,5,6,7],
    [8,9]
]
print(len(c))

3


In [ ]:
import numpy as np
d = np.array([
    [1,2,3],
    [4,5,6,7],
    [8,9]
], dtype=object)

print(d.shape, d.dtype)

# Contar o numero de colunas de cada linha
total_colunas = [len(L) for L in d]
print(total_colunas)

(3,) object
[3, 4, 2]


A biblioteca padrão de Python também tem uma classe *array.array*, mas ela serve apenas pra casos unidimensionais e oferece menos funcionalidades. Os atributos mais importantes do *array* de numpy incluem:

   * array.ndim: o número de eixos do *array*
   * array.shape: as dimensões do *array* na forma de uma tupla indicando o tamanho de cada dimensão; matriz $n \times m$ possui shape $(n, m)$
   * array.size: o número total de elementos no *array*
   * array.dtype: o tipo dos elementos do *array*

### Criando *arrays*

A criação de um *array* pode ser feita usando listas ou tuplas, com o tipo dos dados sendo deduzido através dos tpos dos elementos da sequência. Uma lista de listas resultará em um *array* bidimensional, uma lista de listas de listas dará um *array* tridimensional e assim por diante. É possível especificar o tipo do *array* na hora da criação:

In [ ]:
b = np.array(
    [
        [1., 0., 1.],
        [0., 1., 2.]
    ],
    dtype=complex
)
display(b)

array([[1.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 1.+0.j, 2.+0.j]])

Frequentemente é necessario criar arrays com um tamanho definido e valores iniciais que serão posteriormente modificados. Para isso, NumPy fornece diversas funções, incluindo a função zeros, que cria um array preenchido com zeros; ones, que cria um array preenchido com uns; empty, que cria um array cujo conteúdo inicial é aleatório e depende do estado da memória; e eye, que cria uma matriz identidade.

a + bj

In [ ]:
print(np.zeros((3,4))) # Note que as dimensões são passadas como uma tupla
print()
print(np.ones((3,4)))
print()
print(np.empty((3, 5)))
print()
print(np.eye(3, dtype=np.int32))

Para criar sequências de números, pode-se usar a função *arange*, que é análoga à função *range*, mas retorna *arrays* e aceita criar intervalos de pontos flutuantes.

In [ ]:
#np.arange(start, stop, step)
print(np.arange(5, 20, 2))

print(np.arange(0, 2, 0.4))

[ 5  7  9 11 13 15 17 19]
[0.  0.4 0.8 1.2 1.6]


Devido a possíveis problemas de arredondamento, não é sempre possível saber quantos elementos serão gerados pela função arange ao receber pontos flutuantes como parâmetros. Nesses casos, é melhor usar a função linspace, que recebe como argumentos o início, o fim (inclusivo) e o número de valores desejados no intervalo.

In [ ]:
#np.linspace(start, stop, num)
print(np.linspace(0, 9, 3))

[0.  4.5 9. ]


A função *linspace* é útil para avaliar funções em muitos pontos.

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 100)
f = np.sin(x)

plt.plot(x, f)
plt.show()

### Operações básicas

Operações aritméticas com *arrays* sempre são aplicadas elemento-a-elemento, criando um novo *array* como resultado:

In [ ]:
a = np.array([10, 20, 30, 40])
print(a)
print()
b = np.arange(4)
print(b)

c = a - b
print(c)
print()

print(b ** 2)
print()

print(a < 25)
print()

print(a * b)

d = (a * b) + (a - b) - (b ** 2)
print("Operações múltiplas (a * b) + (a - b) - (b ** 2):", d)

## O operador '\*' multiplica os *arrays* através dos elementos. Para realizar a multiplicação de matrizes, pode-se usar o operador '@', a função *dot* do NumPy, ou o método *dot* do *array*:

In [ ]:
A = np.array(
    [
        [1, 1],
        [0, 1]
    ]
)

B = np.array(
    [
        [2, 0],
        [0, 2]
    ]
)

print(A @ B)
print()
print(np.dot(A, B))
print()
print(A.dot(B))

Elemento(1,1): (1x2) + (1x0) = 2
Elemento(1,2): (1x0) + (1x2) = 2
Elemento(2,1): (0x2) + (1x0) = 0
Elemento(2,2): (0x0) + (1x2) = 2

[1, 1] x [2, 0]
[0, 1]   [0, 2]


Algumas operações, como as de atribuição aritmética "+=" e "\*=", modificam o *array* diretamente, ao invés de criar outro com o resultado.

In [ ]:
A = np.array(
    [
        [1, 1],
        [0, 1]
    ]
)

A += 1
print(A)

[[2 2]
 [1 2]]


Operações com *arrays* de tipos diferentes resultam em um *array* do tipo mais geral ou preciso (*upcasting*). Exemplo:

In [ ]:
a = np.ones(3, dtype=float)
b = np.ones(3, dtype=int)

print((a + b))

[2. 2. 2.]


Muitas operações são computadas como métodos da classe *array*, por exemplo a soma de todos os elementos, a média ou o desvio-padrão:

In [ ]:
a = np.random.random((5, 3)) # Aleatoriza numeros entre ZERO e UM
print(a)

print()
print(
  'Soma: {}, Média: {}, Desvio_Padrão: {}'.format(a.sum(), a.mean(), a.std())
)

[[50.3908806  70.04389742 40.2475854 ]
 [97.80727766 15.32775642 52.48204469]
 [ 0.78707902 72.63007263 66.3260665 ]
 [70.91045294 25.92459328 63.25446101]
 [16.51830169 20.15014202 10.54498036]]

Soma: 673.3455916519499, Média: 44.88970611012999, Desvio_Padrão: 27.762104142694447


In [ ]:
a = np.random.random((5, 3))
b = a *100
print(b)

print()
print(
  'Soma: {}, Média: {}, Desvio_Padrão: {}'.format(b.sum(), b.mean(), b.std())
)

In [ ]:
a = np.random.random((5, 3))
b = a *100

#Arredondar para o inteiro mais proximo
c = np.round(b)
print(c)

print()
print(
  'Soma: {}, Média: {}, Desvio_Padrão: {}'.format(c.sum(), c.mean(), c.std())
)

[[83. 77. 41.]
 [66. 24. 42.]
 [29. 43. 99.]
 [46.  7. 10.]
 [82. 16. 25.]]

Soma: 690.0, Média: 46.0, Desvio_Padrão: 28.06658748999125


In [ ]:
a = np.random.random((5, 3))
b = a *100
print(b)
print()
#Arredondar para baixo
c = np.floor(b)
print(c)

print()
print(
  'Soma: {}, Média: {}, Desvio_Padrão: {}'.format(c.sum(), c.mean(), c.std())
)

[[67.87108174  0.16534557 12.6121018 ]
 [ 6.9656447  12.65182394 96.70507178]
 [88.79979292 29.22619183 98.09460045]
 [26.43694158 41.46191313 35.60477192]
 [64.46171177 12.20241982 99.11215652]]

[[67.  0. 12.]
 [ 6. 12. 96.]
 [88. 29. 98.]
 [26. 41. 35.]
 [64. 12. 99.]]

Soma: 685.0, Média: 45.666666666666664, Desvio_Padrão: 35.175117468018335


In [ ]:
a = np.random.random((5, 3))
b = a *100
print(b)
print()
#Arredondar para cima
c = np.ceil(b)
print(c)

print()
print(
  'Soma: {}, Média: {}, Desvio_Padrão: {}'.format(c.sum(), c.mean(), c.std())
)

Por padrão, essas operações são computadas sobre todos os elementos do *array*, independente das suas dimensões. No entanto, é possível especificar a dimensão desejada, usando o parâmetro *axis*, como mostra o código abaixo:

In [ ]:
a = np.random.random((5, 3))
b = a *100
# print(b)
print()
#Arredondar para cima
c = np.ceil(b)
print(c)
print()
print(c.sum(axis=0)) #Soma de cada coluna
# print(c.sum(axis=1)) #Soma de cada linha
print()

# print(c.mean(axis=0)) #Média de cada coluna
# print(c.mean(axis=1)) #Média de cada linha

#Soma acumulada de cada coluna
print(c.cumsum(axis=0))

In [ ]:
import numpy as np

#Gerar um array de numeros aleatorios no intervalo de (0,1)
a = np.random.random((5,3)) * 50
a = np.ceil(a)
#Transformar o intevalo gerado para (0, 50)
# b = a * 50
print("Array Original")
print(a)

#Calcular a soma acumulada ao longo do eixo 0 (colunas)
soma_acumulada = a.cumsum(axis=0)
print("Soma Acumulada")
print(soma_acumulada)

In [ ]:
import numpy as np

#Gerar um array de numeros aleatorios no intervalo de (0,1)
a = np.ceil(np.random.random((5,3)) * 50)

print("Array Original")
print(a)

#Calcular a soma acumulada ao longo do eixo 0 (colunas)
soma_acumulada = a.cumsum(axis=0)
print("Soma Acumulada")
print(soma_acumulada)

Array Original
[[46.  9. 12.]
 [ 9. 19.  7.]
 [24. 33. 38.]
 [12. 50. 10.]
 [45.  6. 34.]]
Soma Acumulada
[[ 46.   9.  12.]
 [ 55.  28.  19.]
 [ 79.  61.  57.]
 [ 91. 111.  67.]
 [136. 117. 101.]]


Vamos supor que você esteja monitorando as vendas diárias de uma loja e deseja entender a receita acumulada ao longo do mês. O cálculo da soma acumulada pode ajudar a visualizar a receita total acumulada do dia a dia, fornecendo insights sobre o desempenho da loja e facilitando a análise de tendências e padrões de vendas.

In [ ]:
import numpy as np

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.ceil(np.random.random(30) * 1000) # vendas diárias entre 0 e 1000

#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias.cumsum()

print("Vendas Diárias")
display(vendas_diarias)

print("Vendas Acumuladas")
display(vendas_acumuladas)

Vendas Diárias


array([159., 840., 813., 531., 723., 367.,  72., 555., 309., 764., 205.,
       981., 167., 660., 863., 951., 804.,  86., 945., 214., 360., 981.,
       950., 894., 287., 335., 212.,  69., 466., 647.])

Vendas Acumuladas


array([  159.,   999.,  1812.,  2343.,  3066.,  3433.,  3505.,  4060.,
        4369.,  5133.,  5338.,  6319.,  6486.,  7146.,  8009.,  8960.,
        9764.,  9850., 10795., 11009., 11369., 12350., 13300., 14194.,
       14481., 14816., 15028., 15097., 15563., 16210.])

In [ ]:
import numpy as np

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

vendas_diarias_ceil = np.ceil(vendas_diarias * 100) / 100
# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

Vendas Diárias


array([995.84, 403.15, 422.36,  96.01, 507.99, 103.95, 533.63, 415.73,
        47.16, 924.97, 808.63, 851.23, 176.3 , 440.26, 134.  , 754.87,
       357.05, 618.03,  22.92, 360.9 , 690.88, 461.48, 106.95, 796.81,
       580.73, 293.02, 939.25,   2.5 , 350.57, 399.79])

Vendas Acumuladas


array([  995.84,  1398.99,  1821.35,  1917.36,  2425.35,  2529.3 ,
        3062.93,  3478.66,  3525.82,  4450.79,  5259.42,  6110.65,
        6286.95,  6727.21,  6861.21,  7616.08,  7973.13,  8591.16,
        8614.08,  8974.98,  9665.86, 10127.34, 10234.29, 11031.1 ,
       11611.83, 11904.85, 12844.1 , 12846.6 , 13197.17, 13596.96])

In [ ]:
import numpy as np

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

Vendas Diárias


array([373.08, 445.12, 915.74,  75.37, 321.55, 652.04, 231.08, 773.04,
       120.17, 217.47, 572.16, 841.27, 891.11, 350.25, 337.9 , 739.49,
       440.53, 997.79, 549.86, 169.57, 522.75, 388.5 , 175.8 , 302.97,
       499.7 , 826.12, 954.38, 599.92, 573.5 , 424.89])

Vendas Acumuladas


array([  373.08,   818.2 ,  1733.94,  1809.31,  2130.86,  2782.9 ,
        3013.98,  3787.02,  3907.19,  4124.66,  4696.82,  5538.09,
        6429.2 ,  6779.45,  7117.35,  7856.84,  8297.37,  9295.16,
        9845.02, 10014.59, 10537.34, 10925.84, 11101.64, 11404.61,
       11904.31, 12730.43, 13684.81, 14284.73, 14858.23, 15283.12])

In [ ]:
import numpy as np

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)
# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

Vendas Diárias


array([227.2 ,  66.94, 175.43, 154.4 , 534.8 , 975.12, 743.82,   4.87,
       171.05, 984.93, 746.66, 239.8 , 182.37, 752.45, 530.49, 738.24,
       741.35, 157.62, 388.52, 692.02, 957.98, 764.85, 261.01, 570.03,
       957.72, 247.78, 978.56, 277.26, 444.08, 652.41])

Vendas Acumuladas


array([  227.2 ,   294.14,   469.57,   623.97,  1158.77,  2133.89,
        2877.71,  2882.58,  3053.63,  4038.56,  4785.22,  5025.02,
        5207.39,  5959.84,  6490.33,  7228.57,  7969.92,  8127.54,
        8516.06,  9208.08, 10166.06, 10930.91, 11191.92, 11761.95,
       12719.67, 12967.45, 13946.01, 14223.27, 14667.35, 15319.76])

In [ ]:
import numpy as np
import pandas as pd

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)
# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

#Criar um DataFrame com as vendas acumuladas
df_vendas_acumuladas = pd.DataFrame({
    'Dia': np.arange(1, len(vendas_acumuladas) + 1),
    'Vendas Acumuladas': vendas_acumuladas
})

display(df_vendas_acumuladas)

In [ ]:
!pip install pyspark

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, round

# Cria uma sessão Spark
spark = SparkSession.builder.appName("VendasAcumuladas").getOrCreate()

import numpy as np
import pandas as pd

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)
# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

# Criar um DataFrame do PySpark com as vendas acumuladas
vendas_acumuladas_list = [(i + 1, float(vendas_acumuladas[i])) for i in range(len(vendas_acumuladas))]
dfps_vendas_acumuladas = spark.createDataFrame(vendas_acumuladas_list, ["Dia", "Vendas Acumuladas"])

#Exibir DF
dfps_vendas_acumuladas.show()



Vendas Diárias


array([607.45, 547.87, 712.5 , 506.42,   2.16, 831.74, 995.25, 669.75,
       203.56, 964.47, 674.92, 751.52, 735.43, 256.  , 201.6 , 674.76,
       776.89, 131.61, 367.39, 444.71, 347.72, 809.  , 883.82,  31.26,
       826.74, 631.15,  56.35, 894.04, 683.56, 768.47])

Vendas Acumuladas


array([  607.45,  1155.32,  1867.82,  2374.24,  2376.4 ,  3208.14,
        4203.39,  4873.14,  5076.7 ,  6041.17,  6716.09,  7467.61,
        8203.04,  8459.04,  8660.64,  9335.4 , 10112.29, 10243.9 ,
       10611.29, 11056.  , 11403.72, 12212.72, 13096.54, 13127.8 ,
       13954.54, 14585.69, 14642.04, 15536.08, 16219.64, 16988.11])

+---+------------------+
|Dia| Vendas Acumuladas|
+---+------------------+
|  1|            607.45|
|  2|1155.3200000000002|
|  3|1867.8200000000002|
|  4|2374.2400000000002|
|  5|            2376.4|
|  6|3208.1400000000003|
|  7|           4203.39|
|  8|           4873.14|
|  9| 5076.700000000001|
| 10| 6041.170000000001|
| 11| 6716.090000000001|
| 12| 7467.610000000001|
| 13|           8203.04|
| 14|           8459.04|
| 15| 8660.640000000001|
| 16| 9335.400000000001|
| 17|          10112.29|
| 18|10243.900000000001|
| 19|          10611.29|
| 20|           11056.0|
+---+------------------+
only showing top 20 rows



In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, round
from pyspark.sql.types import StructType, StructField, IntegerType, FloatType


# Cria uma sessão Spark
spark = SparkSession.builder.appName("VendasAcumuladas").getOrCreate()

import numpy as np
import pandas as pd

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)

# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

# Criar uma lista de tuplas (Dia, vendas diarias, vendas acumuladas)
vendas_completas_list = [(i + 1, float(vendas_diarias[i]), float(vendas_acumuladas[i])) for i in range(len(vendas_acumuladas))]

#Definir um schema explicitamente
schema = StructType([
    StructField("Dia", IntegerType(), False),
    StructField("Vendas Diárias", FloatType(), False),
    StructField("Vendas Acumuladas", FloatType(), False)
])
# Criar um DataFrame do PySpark com as vendas acumuladas
dfps_vendas_completas = spark.createDataFrame(vendas_completas_list, schema=schema)

#Exibir DF
dfps_vendas_completas.show()


Vendas Diárias


array([547.51, 534.9 , 810.46, 513.53, 162.24, 421.14, 537.45, 477.43,
       336.4 ,  89.07, 655.31, 794.2 , 497.31,  22.6 , 790.8 , 492.01,
       378.36, 262.31,  47.73, 289.28, 254.35, 132.83, 760.64, 531.87,
       774.51, 173.77, 618.49, 786.69, 697.95, 346.76])

Vendas Acumuladas


array([  547.51,  1082.41,  1892.87,  2406.4 ,  2568.64,  2989.78,
        3527.23,  4004.66,  4341.06,  4430.13,  5085.44,  5879.64,
        6376.95,  6399.55,  7190.35,  7682.36,  8060.72,  8323.03,
        8370.76,  8660.04,  8914.39,  9047.22,  9807.86, 10339.73,
       11114.24, 11288.01, 11906.5 , 12693.19, 13391.14, 13737.9 ])

+---+--------------+-----------------+
|Dia|Vendas Diárias|Vendas Acumuladas|
+---+--------------+-----------------+
|  1|      547.5071|           547.51|
|  2|      534.9047|          1082.41|
|  3|      810.4595|          1892.87|
|  4|     513.52966|           2406.4|
|  5|     162.24481|          2568.64|
|  6|     421.14172|          2989.78|
|  7|       537.455|          3527.23|
|  8|     477.43228|          4004.66|
|  9|     336.40366|          4341.06|
| 10|     89.071465|          4430.13|
| 11|     655.30865|          5085.44|
| 12|      794.1974|          5879.64|
| 13|     497.30588|          6376.95|
| 14|     22.598694|          6399.55|
| 15|      790.7981|          7190.35|
| 16|     492.01453|          7682.36|
| 17|     378.36145|          8060.72|
| 18|     262.30832|          8323.03|
| 19|     47.731285|          8370.76|
| 20|     289.28455|          8660.04|
+---+--------------+-----------------+
only showing top 20 rows



In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, round
from pyspark.sql.types import StructType, StructField, IntegerType, FloatType
import matplotlib.pyplot as plt

# Cria uma sessão Spark
spark = SparkSession.builder.appName("VendasAcumuladas").getOrCreate()

import numpy as np
import pandas as pd

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)

# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

# Criar uma lista de tuplas (Dia, vendas diarias, vendas acumuladas)
vendas_completas_list = [(i + 1, float(vendas_diarias[i]), float(vendas_acumuladas[i])) for i in range(len(vendas_acumuladas))]

#Definir um schema explicitamente
schema = StructType([
    StructField("Dia", IntegerType(), False),
    StructField("Vendas Diárias", FloatType(), False),
    StructField("Vendas Acumuladas", FloatType(), False)
])
# Criar um DataFrame do PySpark com as vendas acumuladas
dfps_vendas_completas = spark.createDataFrame(vendas_completas_list, schema=schema)

#Exibir DF
# dfps_vendas_completas.show()

#Convertendo para Pandas
df_vendas_completas = dfps_vendas_completas.toPandas()

#Configurações do Matplotlib
plt.figure(figsize=(10,6))

#Plot das vendas diárias
plt.plot(df_vendas_completas['Dia'], label= 'Vendas Diárias', marker='o' )

#Plot das vendas acumuladas
plt.plot(df_vendas_completas['Dia'], df_vendas_completas['Vendas Acumuladas'], label='Vendas Acumuladas', marker='o')

#Títulos e rótulos
plt.title('Vendas Diárias Acumuladas')
plt.xlabel('Dia')
plt.ylabel('Valor (R$)')
plt.legend()

#Exibir o gráfico
plt.grid(True)
plt.show()

In [ ]:
!pip install streamlit

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, round
from pyspark.sql.types import StructType, StructField, IntegerType, FloatType
import matplotlib.pyplot as plt
import streamlit as st
# Cria uma sessão Spark
spark = SparkSession.builder.appName("VendasAcumuladas").getOrCreate()

import numpy as np
import pandas as pd

#Simulando vendas diárias em um mês (30 dias)
vendas_diarias = np.random.random(30) * 1000 # vendas diárias entre 0 e 1000

# vendas_diarias_ceil = np.round(np.ceil(vendas_diarias * 100) /100, 2)
vendas_diarias_ceil = np.round(vendas_diarias, 2)

# 12.345 * 100 = 12345 / 100  = 123.45
#Calculando a soma acumulada das vendas
vendas_acumuladas = vendas_diarias_ceil.cumsum()

print("Vendas Diárias")
display(vendas_diarias_ceil)

print("Vendas Acumuladas")
display(vendas_acumuladas)

# Criar uma lista de tuplas (Dia, vendas diarias, vendas acumuladas)
vendas_completas_list = [(i + 1, float(vendas_diarias[i]), float(vendas_acumuladas[i])) for i in range(len(vendas_acumuladas))]

#Definir um schema explicitamente
schema = StructType([
    StructField("Dia", IntegerType(), False),
    StructField("Vendas Diárias", FloatType(), False),
    StructField("Vendas Acumuladas", FloatType(), False)
])
# Criar um DataFrame do PySpark com as vendas acumuladas
dfps_vendas_completas = spark.createDataFrame(vendas_completas_list, schema=schema)

#Exibir DF
# dfps_vendas_completas.show()

#Convertendo para Pandas
df_vendas_completas = dfps_vendas_completas.toPandas()

#Configurações do Matplotlib
plt.figure(figsize=(10,6))

#Plot das vendas diárias
plt.plot(df_vendas_completas['Dia'], label= 'Vendas Diárias', marker='o' )

#Plot das vendas acumuladas
plt.plot(df_vendas_completas['Dia'], df_vendas_completas['Vendas Acumuladas'], label='Vendas Acumuladas', marker='o')

#Títulos e rótulos
plt.title('Vendas Diárias Acumuladas')
plt.xlabel('Dia')
plt.ylabel('Valor (R$)')
plt.legend()

#Exibir o gráfico
plt.grid(True)

#Renderizar o gráfico no Streamlit
st.pyplot(plt)

#Exibir os dados a pedido da Carla no  Streamlit
st.write("Dados de vendas Diárias e Acumuladas")
st.dataframe(df_vendas_completas)

### Indexando e iterando sobre elementos

*Arrays* unidimensionais podem ser indexados, fatiados e iterados exatamente como listas e outras coleções.

In [ ]:
a = np.arange(8) * 3
print(a)

print()

print(a[2]) # por indice
print()

print(a[2:5]) # por intervalo de indices
print()

a[:5:2] = - 1000
# a[0] = -1000
# a[2] = -1000
print(a)
print()

for i in a:
  print(i * 2)


Para indexar e iterar sobre elementos de um array do NumPy no Google Colab, você pode usar várias técnicas básicas e avançadas.

##Criando um Array Numpy

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Indexando Elementos

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()
#Acessar um elemento específico(linha, coluna) # Acessar elemento da linha1, coluna2
elemento = array[1,2]
print(elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

6


##Indexação de Fatias (Slicing)

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Acessar uma submatriz (linha1 e 2, todas as colunas)
submatriz = array[1:3, :]
print(submatriz)
print()
#Acessar uma submatriz2 (linha1 e 2, colunas1 e 2)
submatriz2 = array[1:3, 1:3]
print(submatriz2)

##Iterando sobre os elementos

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Iterando sobre os elementos
for linha in array:
  print(linha)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Iterando sobre as linhas e elementos dentro de cada linha
for linha in array:
  for elemento in linha:
    print(elemento, end= ' ')
  print()

##Iterando sobre os elementos individuais

Para iterar sobre os elementos individualmente, podemos usar *np.nditer*

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

for elemento in np.nditer(array):
  print(elemento)

##Uso do Enumerate

*np.ndenumerate*(array)

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

for indice, elemento in np.ndenumerate(array):
  print(f"Índice: {indice}, elemento: {elemento}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Índice: (0, 0), elemento: 1
Índice: (0, 1), elemento: 2
Índice: (0, 2), elemento: 3
Índice: (1, 0), elemento: 4
Índice: (1, 1), elemento: 5
Índice: (1, 2), elemento: 6
Índice: (2, 0), elemento: 7
Índice: (2, 1), elemento: 8
Índice: (2, 2), elemento: 9


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Interando sobre as linhas e elementos dentro de cada linha com indices

for i, linha in enumerate(array):
  for j, elemento in enumerate(linha):
    print(f"Elemento na posição ({i},{j}) é: {elemento}")


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Interando sobre as linhas e elementos dentro de cada linha com indices

for i in range(array.shape[0]):
  for j in range(array.shape[1]):
    print(f"Elemento na posição ({i},{j}) é: {array[i,j]}")


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Interando sobre as linhas e elementos dentro de cada linha com indices

for i in np.ndindex(array.shape):
  print(f"Elemento na posição {i} é: {array[i]}")


##Indexação Booleana

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Criando uma máscara booleana
mask = array > 5
print(mask)
print()

# Usando a máscara booleana para indexar
print(array[mask])

##Indexação por lista de Índices

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3,10,20,30],
    [4,5,6,40,50,60],
    [7,8,9,70,80,90],
    [17,18,19,170,180,190],
    [27,28,29,270,280,290]
])
print(array)
print()

#Acessar elementos nas posições (0,1) e (2,0)
linhas = [0, 2, 3]
colunas = [0, 2, 4]


print(array[linhas, colunas])


#Iteração com controle de Ordem

Iteração em Ordem Fortran(Colunas Primeiro)

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3,10,20,30],
    [4,5,6,40,50,60],
    [7,8,9,70,80,90],
    [17,18,19,170,180,190],
    [27,28,29,270,280,290]
])
print(array)
print()

for elemento in np.nditer(array, order='F'):
  print(elemento)


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Criando listas para armazenar os dados de cada coluna
coluna_1 = []
coluna_2 = []
coluna_3 = []
#2 esta na coluna 2 % 3 = 2
#Iteração sobre os elementos na ordem de coluna
for idx, elemento in enumerate (np.nditer(array)):
  if idx % 3 == 0:
    coluna_1.append(int(elemento))
  elif idx % 3 == 1:
    coluna_2.append(int(elemento))
  else:
    coluna_3.append(int(elemento))

#Criando o Dataframe com os dados de cada coluna em pandas
import pandas as pd

dfpd = pd.DataFrame({
    'Coluna_1': coluna_1,
    'Coluna_2': coluna_2,
    'Coluna_3': coluna_3
})

display(dfpd)



[[1 2 3]
 [4 5 6]
 [7 8 9]]



Coluna_1  Coluna_2  Coluna_3
0         1         2         3
1         4         5         6
2         7         8         9

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Criando listas para armazenar os dados de cada coluna
coluna_1 = []
coluna_2 = []
coluna_3 = []
#2 esta na coluna 2 % 3 = 2
#Iteração sobre os elementos na ordem de coluna
for idx, elemento in enumerate (np.nditer(array, order="F")):
  # if idx % 3 == 0:
  #   coluna_1.append(int(elemento))
  # elif idx % 3 == 1:
  #   coluna_2.append(int(elemento))
  # else:
  #   coluna_3.append(int(elemento))

   if idx == 0:
    coluna_1.append(int(elemento))
   elif idx == 1:
    coluna_2.append(int(elemento))
   elif idx == 2:
    coluna_3.append(int(elemento))

#Criando o Dataframe com os dados de cada coluna em pandas
import pandas as pd

dfpd = pd.DataFrame({
    'Coluna_1': coluna_1,
    'Coluna_2': coluna_2,
    'Coluna_3': coluna_3
})

display(dfpd)
print()

#Transformando o DataFrame em um Array Numpy
novo_array = dfpd.to_numpy()

print(novo_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



Coluna_1  Coluna_2  Coluna_3
0         1         4         7
1         2         5         8
2         3         6         9


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

# Transpondo o array para facilitar a extração de colunas
transposto_array = array.T

#Separando as colunas em listas
coluna_1, coluna_2, coluna_3 = [list(coluna) for coluna in transposto_array]

#Criando o Dataframe com os dados de cada coluna em pandas
import pandas as pd

dfpd = pd.DataFrame({
    'Coluna_1': coluna_1,
    'Coluna_2': coluna_2,
    'Coluna_3': coluna_3
})

display(dfpd)


[[1 2 3]
 [4 5 6]
 [7 8 9]]



Coluna_1  Coluna_2  Coluna_3
0         1         2         3
1         4         5         6
2         7         8         9

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3, 99, 100, 2],
    [4,5,6, 200, 300, 9],
    [7,8,9, 400, 500, 7]
])
print(array)
print()

#Obter o número de colunas
num_colunas = array.shape[1]
# print(num_colunas)

#Criar uma lista de listas para armazenas os dados de cada coluna
colunas = [[] for _ in range(num_colunas)]

#Iterar sobre os elementos do array e distribuí-los nas colunas
for linha in array:
  for indice, valor in enumerate(linha):
    colunas[indice].append(valor)

#Exibir as colunas
for i, coluna in enumerate(colunas, start=1):
  print(f"Coluna {i}:", coluna)

#Criar um DataFrame a partir das colunas
import pandas as pd
dfpd = pd.DataFrame({f'Coluna_{i+1}': colunas[i] for i in range(num_colunas)})

#Exibindo DataFrame
display(dfpd)

[[  1   2   3  99 100   2]
 [  4   5   6 200 300   9]
 [  7   8   9 400 500   7]]

Coluna 1: [1, 4, 7]
Coluna 2: [2, 5, 8]
Coluna 3: [3, 6, 9]
Coluna 4: [99, 200, 400]
Coluna 5: [100, 300, 500]
Coluna 6: [2, 9, 7]


Coluna_1  Coluna_2  Coluna_3  Coluna_4  Coluna_5  Coluna_6
0         1         2         3        99       100         2
1         4         5         6       200       300         9
2         7         8         9       400       500         7

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

# Criar um array 2D com strings
array = np.array([
    ["maçã", "banana", "cereja"],
    ["laranja", "uva", "manga"]
])
print(array)
print()

#Obter o número de colunas
num_colunas = array.shape[1]
# print(num_colunas)

#Criar uma lista de listas para armazenas os dados de cada coluna
colunas = [[] for _ in range(num_colunas)]

#Iterar sobre os elementos do array e distribuí-los nas colunas
for linha in array:
  for indice, valor in enumerate(linha):
    colunas[indice].append(valor)

#Exibir as colunas
for i, coluna in enumerate(colunas, start=1):
  print(f"Coluna {i}:", coluna)

#Criar um DataFrame a partir das colunas
import pandas as pd
dfpd = pd.DataFrame({f'Coluna_{i+1}': colunas[i] for i in range(num_colunas)})

#Exibindo DataFrame
display(dfpd)

[['maçã' 'banana' 'cereja']
 ['laranja' 'uva' 'manga']]

Coluna 1: ['maçã', 'laranja']
Coluna 2: ['banana', 'uva']
Coluna 3: ['cereja', 'manga']


Coluna_1 Coluna_2 Coluna_3
0     maçã   banana   cereja
1  laranja      uva    manga

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

# Criar um array 2D com diferentes tipos usando dtype=object
array = np.array([
    [10, "texto", 3.14],
    [True, 42, "outra string"]
], dtype=object)

print(array)
print()

#Obter o número de colunas
num_colunas = array.shape[1]
# print(num_colunas)

#Criar uma lista de listas para armazenas os dados de cada coluna
colunas = [[] for _ in range(num_colunas)]

#Iterar sobre os elementos do array e distribuí-los nas colunas
for linha in array:
  for indice, valor in enumerate(linha):
    colunas[indice].append(valor)

#Exibir as colunas
for i, coluna in enumerate(colunas, start=1):
  print(f"Coluna {i}:", coluna)

#Criar um DataFrame a partir das colunas
import pandas as pd
dfpd = pd.DataFrame({f'Coluna_{i+1}': colunas[i] for i in range(num_colunas)})

#Exibindo DataFrame
display(dfpd)

##Iteração com numpy.apply_along_axis

In [ ]:
import numpy as np
#Criando um array 2D(matriz)

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array)
print()

#Função para somar todos os elementos de uma linha
def soma_linha(linha):
  return np.sum(linha)

# def media_linha(linha):
#   return np.mean(linha)

#Aplicar a função ao longo das linhas (axis=1)
resultado = np.apply_along_axis(soma_linha, axis=1, arr=array)

print(resultado)
print()
#Aplicar a função ao longo das colunas (axis=0)
resultado2 = np.apply_along_axis(soma_linha, axis=0, arr=array)

print(resultado2)

##Importar um CSV para um array numpy

Usar a função *numpy.genfromtxt()* ou *numpy.loadtxt()*



*   **numpy.genfromtxt()**: é mais flexivél e pode lidar com arquivos CSV que contêm, cabeçalhos ou valores ausentes.
*   **numpy.loadtxt()**: é mais simples, mas não lida bem com cabeçalhos e valores ausentes.



In [ ]:
import numpy as np

#Caminho para o arquivo CSV
arquivo_csv = '/content/funcionarios.csv'

#Importar CSV para um array NumPy
array = np.genfromtxt(arquivo_csv, delimiter=', ', dtype=object, skip_header=1)

print("Array NumPy Importado")
print(array)

Array NumPy Importado
[b'41,Sim,Viaja raramente,1102,Vendas,1,2,Ci\xeancias Humanas,1,1,2,Feminino,94,3,2,Executivo de vendas,4,Solteiro,5993,19479,8,Sim,Sim,11,3,1,80,0,8,0,1,6,4,0,5'
 b'49,N\xe3o,Viaja frequentemente,279,Pesquisa e Desenvolvimento,8,1,Ci\xeancias Humanas,1,2,3,Masculino,61,2,2,Pesquisador cientista,2,Casado,5130,24907,1,Sim,N\xe3o,23,4,4,80,1,10,3,3,10,7,1,7'
 b'37,Sim,Viaja raramente,1373,Pesquisa e Desenvolvimento,2,2,Outras,1,4,4,Masculino,92,2,1,T\xe9cnico de Laborat\xf3rio,3,Solteiro,2090,2396,6,Sim,Sim,15,3,2,80,0,7,3,3,0,0,0,0'
 ...
 b'27,N\xe3o,Viaja raramente,155,Pesquisa e Desenvolvimento,4,3,Ci\xeancias Humanas,1,2064,2,Masculino,87,4,2,Diretor de manufatura,2,Casado,6142,5174,1,Sim,Sim,20,4,2,80,1,6,0,3,6,2,0,3'
 b'49,N\xe3o,Viaja frequentemente,1023,Vendas,2,3,Ci\xeancias M\xe9dicas,1,2065,4,Masculino,63,2,2,Executivo de vendas,2,Casado,5390,13243,2,Sim,N\xe3o,14,3,4,80,0,17,3,2,9,6,0,8'
 b'34,N\xe3o,Viaja raramente,628,Pesquisa e Desenvolvimento,8,3,Ci\

In [ ]:
import numpy as np

#Caminho para o arquivo CSV
arquivo_csv = '/content/funcionarios.csv'

#Importar CSV para um array NumPy
array = np.loadtxt(arquivo_csv, delimiter=', ', skiprows=1)

print("Array NumPy Importado")
print(array)

##Broadcasting e Operações com arrays

In [ ]:
import numpy as np

#Criar um array de 1D
array1d = np.array([1,2,3])

#Criar um array 2D
array2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#Somar o array 1D a cada linha do array 2D
resultado = array2d + array1d

print(resultado)

##Exemplo Real: Ajuste de Preços em um catálogo de Produtos

Imagine que você tem um catálogo de produtos com seus preços em diferentes lojas. Suponha que você tenha um array 2D onde cada linha representa os preços de um produto em várias lojas e um array 1D com uma taxa de ajuste de preço para cada loja.

**Objetivo** Atualizar os preços de cada produto adicionando um ajuste de preço específico para cada loja

In [ ]:
#Passo 01 - Definir os Dados
## Array 2D: Preços dos produtos em várias lojas
## Array 1D: Ajuste de preço para cada loja

import numpy as np
#Preços dos produtos em diferentes lojas
precos = np.array([
    [10.0, 20.0, 30.0], # Preços do produto 1 em lojas 1, 2 e 3
    [15.0, 25.0, 35.0], # Preços do produto 2 em lojas 1, 2 e 3
    [20.0, 30.0, 40.0]  # Preços do produto 3 em lojas 1, 2 e 3
])

#Ajuste de preço para cada loja
ajuste_preco = np.array([1.2, 1.3, 1.4]) # ajustes para as lojas 1, 2 e 3

#Atualizar os preços dos produtos
precos_atualizados = precos * ajuste_preco

print("Preços Originais:")
print(precos)
print()
print("\nAjuste de preço:")
print(ajuste_preco)
print("\nPreços Atualizados:")
print(precos_atualizados)

In [ ]:
import numpy as np

# Salários dos funcionários em diferentes departamentos
salarios = np.array([
    [50000, 52000, 54000],  # Salários no Departamento A
    [60000, 62000, 64000],  # Salários no Departamento B
    [70000, 72000, 74000]   # Salários no Departamento C
])

# Percentuais de aumento para cada departamento
aumento_percentual = np.array([0.05, 0.07, 0.10])  # 5%, 7%, e 10%

#Atualizar os salarios para cada departamento
salarios_ajustados = salarios * (1 - aumento_percentual)

print("Salarios Originais:")
print(salarios)
print()
print("\nAjuste Percentual:")
print(aumento_percentual)
print("\nSalarios Atualizados:")
print(salarios_ajustados)

Salarios Originais:
[[50000 52000 54000]
 [60000 62000 64000]
 [70000 72000 74000]]


Ajuste Percentual:
[0.05 0.07 0.1 ]

Salarios Atualizados:
[[47500. 48360. 48600.]
 [57000. 57660. 57600.]
 [66500. 66960. 66600.]]


In [ ]:
import numpy as np

# Salários dos funcionários em diferentes departamentos
salarios = np.array([
    [50000, 52000, 54000],  # Salários no Departamento A
    [60000, 62000, 64000],  # Salários no Departamento B
    [70000, 72000, 74000]   # Salários no Departamento C
])

# Percentuais de aumento para cada departamento
aumento_percentual = np.array([0.05, 0.07, 0.10])  # 5%, 7%, e 10%

#Atualizar os salarios para cada departamento
salarios_ajustados = salarios * (1 - aumento_percentual)

# print("Salarios Originais:")
# print(salarios)
# print()
# print("\nAjuste Percentual:")
# print(aumento_percentual)
# print("\nSalarios Atualizados:")
# print(salarios_ajustados)

# salarios_ajustados[:, np.newaxis]

array([[[47500., 48360., 48600.]],

       [[57000., 57660., 57600.]],

       [[66500., 66960., 66600.]]])

##Concatenação de Arrays

As funções vstack e hstack, permitem concatenar dois ou mais arrays verticamente e horizontalmente

In [ ]:
import numpy as np

#Criando dois arrays 1D
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

#Concatenar os arrays verticalmente de 1D
resultado_vstack = np.vstack((array1, array2))
# print(resultado_vstack)

#Criando dois arrays 2D
array3 = np.array([
    [1,2,3],
    [4,5,6]
])
array4 = np.array([
    [7,8,9],
    [10,11,12]
])
#Concatenar os arrays verticalmente de 2D
resultado_vstack_2D = np.vstack((array3, array4 ))
print(resultado_vstack_2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

#Criando dois arrays 1D
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

#Concatenar os arrays Horizontalmente de 1D
resultado_hstack = np.hstack((array1, array2))
print(resultado_hstack)

#Criando dois arrays 2D
array3 = np.array([
    [1,2,3],
    [4,5,6]
])
array4 = np.array([
    [7,8,9],
    [10,11,12]
])
#Concatenar os arrays Horizontalmente de 2D
resultado_hstack_2D = np.hstack((array3, array4))
print(resultado_hstack_2D)

[1 2 3 4 5 6]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
